site_name: jqfactor_analyzer
site_author: JQ-PM
theme: readthedocs
repo_url: https://github.com/HouZijiao/ja
copyright: 聚宽

nav:
    - Home: 'index.md'
    - 标题1: 'test.md'
    - API文档: 'api文档.md'
    - User Guide:
      - 'Writing your docs': 'test.md'